"""Database schema for training metrics."""

SCHEMA = """
-- User profile for personalized calculations
CREATE TABLE IF NOT EXISTS user_profile (
    id INTEGER PRIMARY KEY DEFAULT 1,
    max_hr INTEGER,
    rest_hr INTEGER,
    threshold_hr INTEGER,
    gender TEXT DEFAULT 'male',
    age INTEGER,
    weight_kg REAL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Daily fitness metrics (one row per day)
CREATE TABLE IF NOT EXISTS fitness_metrics (
    date TEXT PRIMARY KEY,
    daily_load REAL,
    ctl REAL,
    atl REAL,
    tsb REAL,
    acwr REAL,
    risk_zone TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Enriched activity data (supplements n8n raw_activities)
CREATE TABLE IF NOT EXISTS activity_metrics (
    activity_id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    activity_type TEXT,
    activity_name TEXT,
    hrss REAL,
    trimp REAL,
    avg_hr INTEGER,
    max_hr INTEGER,
    duration_min REAL,
    distance_km REAL,
    pace_sec_per_km REAL,
    zone1_pct REAL,
    zone2_pct REAL,
    zone3_pct REAL,
    zone4_pct REAL,
    zone5_pct REAL,
    -- Multi-sport extensions (Phase 2)
    sport_type TEXT,
    avg_power INTEGER,
    max_power INTEGER,
    normalized_power INTEGER,
    tss REAL,
    intensity_factor REAL,
    variability_index REAL,
    avg_speed_kmh REAL,
    elevation_gain_m REAL,
    cadence INTEGER,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create index on date for efficient queries
CREATE INDEX IF NOT EXISTS idx_activity_metrics_date ON activity_metrics(date);
CREATE INDEX IF NOT EXISTS idx_fitness_metrics_date ON fitness_metrics(date);
CREATE INDEX IF NOT EXISTS idx_activity_metrics_sport_type ON activity_metrics(sport_type);

-- =============================================================================
-- Phase 2: Multi-sport Extensions - Power Zones Table
-- =============================================================================

-- Power zones for cycling/running power metrics
CREATE TABLE IF NOT EXISTS power_zones (
    athlete_id TEXT PRIMARY KEY,
    ftp INTEGER,
    zone1_max INTEGER,
    zone2_max INTEGER,
    zone3_max INTEGER,
    zone4_max INTEGER,
    zone5_max INTEGER,
    zone6_max INTEGER,
    zone7_max INTEGER,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- Phase 2: Multi-sport Extensions - Swim Metrics Table
-- =============================================================================

-- Swimming-specific metrics per activity
CREATE TABLE IF NOT EXISTS swim_metrics (
    activity_id TEXT PRIMARY KEY,
    pool_length_m INTEGER,
    total_strokes INTEGER,
    avg_swolf REAL,
    avg_stroke_rate REAL,
    css_pace_sec INTEGER,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (activity_id) REFERENCES activity_metrics(activity_id)
);

-- Create index for swim metrics
CREATE INDEX IF NOT EXISTS idx_swim_metrics_activity ON swim_metrics(activity_id);

-- Race goals table for tracking target races
CREATE TABLE IF NOT EXISTS race_goals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    race_date TEXT NOT NULL,
    distance TEXT NOT NULL,
    target_time_sec INTEGER NOT NULL,
    notes TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Weekly summaries for historical analysis
CREATE TABLE IF NOT EXISTS weekly_summaries (
    week_start TEXT PRIMARY KEY,
    total_distance_km REAL,
    total_duration_min REAL,
    total_load REAL,
    activity_count INTEGER,
    zone_distribution TEXT,  -- JSON with zone1_pct through zone5_pct
    ctl_start REAL,
    ctl_end REAL,
    ctl_change REAL,
    atl_change REAL,
    week_over_week_change REAL,
    is_recovery_week INTEGER DEFAULT 0,
    insights TEXT,           -- JSON array of insight strings
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for new tables
CREATE INDEX IF NOT EXISTS idx_race_goals_date ON race_goals(race_date);
CREATE INDEX IF NOT EXISTS idx_weekly_summaries_start ON weekly_summaries(week_start);

-- =============================================================================
-- Phase 1: Database Persistence - New Tables
-- =============================================================================

-- Structured workouts designed by the workout agent
CREATE TABLE IF NOT EXISTS workouts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    sport TEXT NOT NULL DEFAULT 'running',
    intervals_json TEXT NOT NULL,  -- JSON array of workout intervals
    estimated_duration_min INTEGER NOT NULL,
    estimated_distance_m INTEGER,
    estimated_load REAL DEFAULT 0.0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Index for efficient workout queries
CREATE INDEX IF NOT EXISTS idx_workouts_created_at ON workouts(created_at);
CREATE INDEX IF NOT EXISTS idx_workouts_sport ON workouts(sport);

-- Training plans generated by the plan agent
CREATE TABLE IF NOT EXISTS training_plans (
    id TEXT PRIMARY KEY,
    name TEXT,
    description TEXT,
    goal_json TEXT NOT NULL,           -- JSON object with race goal details
    periodization TEXT NOT NULL,        -- linear, reverse, block, undulating
    peak_week INTEGER NOT NULL,
    total_weeks INTEGER NOT NULL,
    weeks_json TEXT NOT NULL,          -- JSON array of training weeks
    athlete_context_json TEXT,         -- JSON object with athlete context
    constraints_json TEXT,             -- JSON object with plan constraints
    phases_summary_json TEXT,          -- JSON object with phase counts
    total_planned_load REAL,
    is_active INTEGER DEFAULT 0,
    adaptation_history_json TEXT,      -- JSON array of adaptations
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for efficient plan queries
CREATE INDEX IF NOT EXISTS idx_training_plans_created_at ON training_plans(created_at);
CREATE INDEX IF NOT EXISTS idx_training_plans_is_active ON training_plans(is_active);
CREATE INDEX IF NOT EXISTS idx_training_plans_goal_race_date ON training_plans(json_extract(goal_json, '$.race_date'));

-- Workout analyses - permanent storage for AI-generated workout insights
CREATE TABLE IF NOT EXISTS workout_analyses (
    workout_id TEXT PRIMARY KEY,       -- References activity_metrics.activity_id
    summary TEXT NOT NULL,             -- Main analysis summary
    what_went_well TEXT,               -- JSON array of positive observations
    improvements TEXT,                 -- JSON array of areas for improvement
    training_context TEXT,             -- How workout fits into training
    execution_rating TEXT,             -- excellent, good, fair, needs_improvement
    overall_score INTEGER,             -- 0-100 overall score
    training_effect_score REAL,        -- Training effect (1.0-5.0)
    load_score INTEGER,                -- Load score (0-100+)
    recovery_hours INTEGER,            -- Recommended recovery time
    model_used TEXT,                   -- LLM model used for analysis
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Index for efficient queries
CREATE INDEX IF NOT EXISTS idx_workout_analyses_created ON workout_analyses(created_at);

-- =============================================================================
-- Garmin Fitness Data - VO2max, Race Predictions, Training Status
-- =============================================================================

-- Daily fitness data from Garmin (VO2max, race predictions, training status)
-- One record per day to track historical changes
CREATE TABLE IF NOT EXISTS garmin_fitness_data (
    date TEXT PRIMARY KEY,
    -- VO2max metrics
    vo2max_running REAL,           -- Running VO2max (precise value)
    vo2max_cycling REAL,           -- Cycling VO2max if available
    fitness_age INTEGER,           -- Garmin's fitness age estimate
    -- Race predictions (times in seconds)
    race_time_5k INTEGER,          -- 5K predicted time in seconds
    race_time_10k INTEGER,         -- 10K predicted time in seconds
    race_time_half INTEGER,        -- Half marathon predicted time in seconds
    race_time_marathon INTEGER,    -- Marathon predicted time in seconds
    -- Training status
    training_status TEXT,          -- PRODUCTIVE, UNPRODUCTIVE, PEAKING, RECOVERY, etc.
    training_status_description TEXT, -- Human-readable description
    fitness_trend TEXT,            -- IMPROVING, MAINTAINING, DECLINING
    -- Training readiness
    training_readiness_score INTEGER,  -- 0-100 readiness score
    training_readiness_level TEXT,     -- HIGH, MODERATE, LOW, POOR
    -- Acute:Chronic Workload Ratio
    acwr_percent REAL,             -- ACWR percentage
    acwr_status TEXT,              -- Status (OPTIMAL, HIGH_RISK, LOW, etc.)
    -- Metadata
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create index for efficient date-based queries
CREATE INDEX IF NOT EXISTS idx_garmin_fitness_date ON garmin_fitness_data(date);

-- Insert default profile if not exists (using INSERT OR IGNORE)
INSERT OR IGNORE INTO user_profile (id, max_hr, rest_hr, threshold_hr, age, gender)
VALUES (1, 185, 55, 165, 30, 'male');
"""

# Separate schema for updating user profile
UPDATE_PROFILE_SQL = """
INSERT OR REPLACE INTO user_profile (id, max_hr, rest_hr, threshold_hr, age, gender, weight_kg, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
"""
