"""Database schema for training metrics."""

SCHEMA = """
-- User profile for personalized calculations
CREATE TABLE IF NOT EXISTS user_profile (
    id INTEGER PRIMARY KEY DEFAULT 1,
    max_hr INTEGER,
    rest_hr INTEGER,
    threshold_hr INTEGER,
    gender TEXT DEFAULT 'male',
    age INTEGER,
    weight_kg REAL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Daily fitness metrics (one row per day)
CREATE TABLE IF NOT EXISTS fitness_metrics (
    date TEXT PRIMARY KEY,
    daily_load REAL,
    ctl REAL,
    atl REAL,
    tsb REAL,
    acwr REAL,
    risk_zone TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Enriched activity data (supplements n8n raw_activities)
CREATE TABLE IF NOT EXISTS activity_metrics (
    activity_id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    activity_type TEXT,
    activity_name TEXT,
    hrss REAL,
    trimp REAL,
    avg_hr INTEGER,
    max_hr INTEGER,
    duration_min REAL,
    distance_km REAL,
    pace_sec_per_km REAL,
    zone1_pct REAL,
    zone2_pct REAL,
    zone3_pct REAL,
    zone4_pct REAL,
    zone5_pct REAL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create index on date for efficient queries
CREATE INDEX IF NOT EXISTS idx_activity_metrics_date ON activity_metrics(date);
CREATE INDEX IF NOT EXISTS idx_fitness_metrics_date ON fitness_metrics(date);

-- Race goals table for tracking target races
CREATE TABLE IF NOT EXISTS race_goals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    race_date TEXT NOT NULL,
    distance TEXT NOT NULL,
    target_time_sec INTEGER NOT NULL,
    notes TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Weekly summaries for historical analysis
CREATE TABLE IF NOT EXISTS weekly_summaries (
    week_start TEXT PRIMARY KEY,
    total_distance_km REAL,
    total_duration_min REAL,
    total_load REAL,
    activity_count INTEGER,
    zone_distribution TEXT,  -- JSON with zone1_pct through zone5_pct
    ctl_start REAL,
    ctl_end REAL,
    ctl_change REAL,
    atl_change REAL,
    week_over_week_change REAL,
    is_recovery_week INTEGER DEFAULT 0,
    insights TEXT,           -- JSON array of insight strings
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for new tables
CREATE INDEX IF NOT EXISTS idx_race_goals_date ON race_goals(race_date);
CREATE INDEX IF NOT EXISTS idx_weekly_summaries_start ON weekly_summaries(week_start);

-- =============================================================================
-- Phase 1: Database Persistence - New Tables
-- =============================================================================

-- Structured workouts designed by the workout agent
CREATE TABLE IF NOT EXISTS workouts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    sport TEXT NOT NULL DEFAULT 'running',
    intervals_json TEXT NOT NULL,  -- JSON array of workout intervals
    estimated_duration_min INTEGER NOT NULL,
    estimated_distance_m INTEGER,
    estimated_load REAL DEFAULT 0.0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Index for efficient workout queries
CREATE INDEX IF NOT EXISTS idx_workouts_created_at ON workouts(created_at);
CREATE INDEX IF NOT EXISTS idx_workouts_sport ON workouts(sport);

-- Training plans generated by the plan agent
CREATE TABLE IF NOT EXISTS training_plans (
    id TEXT PRIMARY KEY,
    name TEXT,
    description TEXT,
    goal_json TEXT NOT NULL,           -- JSON object with race goal details
    periodization TEXT NOT NULL,        -- linear, reverse, block, undulating
    peak_week INTEGER NOT NULL,
    total_weeks INTEGER NOT NULL,
    weeks_json TEXT NOT NULL,          -- JSON array of training weeks
    athlete_context_json TEXT,         -- JSON object with athlete context
    constraints_json TEXT,             -- JSON object with plan constraints
    phases_summary_json TEXT,          -- JSON object with phase counts
    total_planned_load REAL,
    is_active INTEGER DEFAULT 0,
    adaptation_history_json TEXT,      -- JSON array of adaptations
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for efficient plan queries
CREATE INDEX IF NOT EXISTS idx_training_plans_created_at ON training_plans(created_at);
CREATE INDEX IF NOT EXISTS idx_training_plans_is_active ON training_plans(is_active);
CREATE INDEX IF NOT EXISTS idx_training_plans_goal_race_date ON training_plans(json_extract(goal_json, '$.race_date'));

-- LLM analysis result cache to save API costs
CREATE TABLE IF NOT EXISTS analysis_cache (
    cache_key TEXT PRIMARY KEY,        -- Hash of input parameters
    analysis_type TEXT NOT NULL,       -- Type of analysis (workout, weekly, etc.)
    input_hash TEXT NOT NULL,          -- Hash of the input data for validation
    result_json TEXT NOT NULL,         -- Cached analysis result
    model_name TEXT,                   -- LLM model used for analysis
    tokens_used INTEGER,               -- Token count for cost tracking
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT,                   -- Optional expiration timestamp
    hit_count INTEGER DEFAULT 0        -- Track cache hits for analytics
);

-- Indexes for efficient cache lookups
CREATE INDEX IF NOT EXISTS idx_analysis_cache_type ON analysis_cache(analysis_type);
CREATE INDEX IF NOT EXISTS idx_analysis_cache_expires ON analysis_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_analysis_cache_input_hash ON analysis_cache(input_hash);

-- Insert default profile if not exists (using INSERT OR IGNORE)
INSERT OR IGNORE INTO user_profile (id, max_hr, rest_hr, threshold_hr, age, gender)
VALUES (1, 185, 55, 165, 30, 'male');
"""

# Separate schema for updating user profile
UPDATE_PROFILE_SQL = """
INSERT OR REPLACE INTO user_profile (id, max_hr, rest_hr, threshold_hr, age, gender, weight_kg, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
"""
